TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

LIBS += -L$$PWD/lib/ -lmingw32 -lSDL2main -lSDL2

SOURCES += \
        ../LVGL-APP/lvgl_app.c \
        ../Third_Party/LVGL/lvgl/examples/anim/lv_example_anim_1.c \
        ../Third_Party/LVGL/lvgl/examples/anim/lv_example_anim_2.c \
        ../Third_Party/LVGL/lvgl/examples/anim/lv_example_anim_3.c \
        ../Third_Party/LVGL/lvgl/examples/anim/lv_example_anim_timeline_1.c \
        ../Third_Party/LVGL/lvgl/examples/assets/animimg001.c \
        ../Third_Party/LVGL/lvgl/examples/assets/animimg002.c \
        ../Third_Party/LVGL/lvgl/examples/assets/animimg003.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_caret_down.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_cogwheel_alpha16.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_cogwheel_argb.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_cogwheel_chroma_keyed.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_cogwheel_indexed16.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_cogwheel_rgb.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_hand.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_skew_strip.c \
        ../Third_Party/LVGL/lvgl/examples/assets/img_star.c \
        ../Third_Party/LVGL/lvgl/examples/assets/imgbtn_left.c \
        ../Third_Party/LVGL/lvgl/examples/assets/imgbtn_mid.c \
        ../Third_Party/LVGL/lvgl/examples/assets/imgbtn_right.c \
        ../Third_Party/LVGL/lvgl/examples/event/lv_example_event_1.c \
        ../Third_Party/LVGL/lvgl/examples/event/lv_example_event_2.c \
        ../Third_Party/LVGL/lvgl/examples/event/lv_example_event_3.c \
        ../Third_Party/LVGL/lvgl/examples/get_started/lv_example_get_started_1.c \
        ../Third_Party/LVGL/lvgl/examples/get_started/lv_example_get_started_2.c \
        ../Third_Party/LVGL/lvgl/examples/get_started/lv_example_get_started_3.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_1.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_2.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_3.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_4.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_5.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex_6.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_1.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_2.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_3.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_4.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_5.c \
        ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid_6.c \
        ../Third_Party/LVGL/lvgl/examples/libs/bmp/lv_example_bmp_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/freetype/lv_example_freetype_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/gif/img_bulb_gif.c \
        ../Third_Party/LVGL/lvgl/examples/libs/gif/lv_example_gif_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/png/img_wing_png.c \
        ../Third_Party/LVGL/lvgl/examples/libs/png/lv_example_png_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/qrcode/lv_example_qrcode_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/rlottie/lv_example_rlottie_1.c \
        ../Third_Party/LVGL/lvgl/examples/libs/rlottie/lv_example_rlottie_2.c \
        ../Third_Party/LVGL/lvgl/examples/libs/rlottie/lv_example_rlottie_approve.c \
        ../Third_Party/LVGL/lvgl/examples/libs/sjpg/lv_example_sjpg_1.c \
        ../Third_Party/LVGL/lvgl/examples/others/snapshot/lv_example_snapshot_1.c \
        ../Third_Party/LVGL/lvgl/examples/porting/lv_port_disp_template.c \
        ../Third_Party/LVGL/lvgl/examples/porting/lv_port_fs_template.c \
        ../Third_Party/LVGL/lvgl/examples/porting/lv_port_indev_template.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_1.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_2.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_3.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_4.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_5.c \
        ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll_6.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_1.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_10.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_11.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_12.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_13.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_14.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_2.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_3.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_4.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_5.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_6.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_7.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_8.c \
        ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style_9.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/animimg/lv_example_animimg_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/arc/lv_example_arc_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/arc/lv_example_arc_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_4.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_5.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/bar/lv_example_bar_6.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btn/lv_example_btn_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btn/lv_example_btn_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btn/lv_example_btn_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/calendar/lv_example_calendar_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/canvas/lv_example_canvas_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/canvas/lv_example_canvas_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_4.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_5.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_6.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_7.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_8.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/chart/lv_example_chart_9.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/checkbox/lv_example_checkbox_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/colorwheel/lv_example_colorwheel_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/dropdown/lv_example_dropdown_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/dropdown/lv_example_dropdown_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/dropdown/lv_example_dropdown_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/img/lv_example_img_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/img/lv_example_img_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/img/lv_example_img_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/img/lv_example_img_4.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/imgbtn/lv_example_imgbtn_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/keyboard/lv_example_keyboard_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/label/lv_example_label_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/label/lv_example_label_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/label/lv_example_label_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/label/lv_example_label_4.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/led/lv_example_led_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/line/lv_example_line_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/list/lv_example_list_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/list/lv_example_list_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/meter/lv_example_meter_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/meter/lv_example_meter_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/meter/lv_example_meter_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/meter/lv_example_meter_4.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/obj/lv_example_obj_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/obj/lv_example_obj_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/roller/lv_example_roller_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/roller/lv_example_roller_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/roller/lv_example_roller_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/slider/lv_example_slider_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/slider/lv_example_slider_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/slider/lv_example_slider_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/span/lv_example_span_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/spinbox/lv_example_spinbox_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/spinner/lv_example_spinner_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/switch/lv_example_switch_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/table/lv_example_table_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/table/lv_example_table_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/tabview/lv_example_tabview_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/tabview/lv_example_tabview_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/textarea/lv_example_textarea_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/textarea/lv_example_textarea_2.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/textarea/lv_example_textarea_3.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/tileview/lv_example_tileview_1.c \
        ../Third_Party/LVGL/lvgl/examples/widgets/win/lv_example_win_1.c \
        ../Third_Party/LVGL/lvgl/rt-thread/lv_rt_thread_port.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_disp.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_event.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_group.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_indev.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_indev_scroll.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_class.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_draw.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_pos.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_scroll.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_style.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_style_gen.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_obj_tree.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_refr.c \
        ../Third_Party/LVGL/lvgl/src/core/lv_theme.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_arc.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_blend.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_img.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_label.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_line.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_mask.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_rect.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_draw_triangle.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_img_buf.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_img_cache.c \
        ../Third_Party/LVGL/lvgl/src/draw/lv_img_decoder.c \
        ../Third_Party/LVGL/lvgl/src/extra/layouts/flex/lv_flex.c \
        ../Third_Party/LVGL/lvgl/src/extra/layouts/grid/lv_grid.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/bmp/lv_bmp.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/freetype/lv_freetype.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/gif/gifdec.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/gif/lv_gif.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/png/lodepng.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/png/lv_png.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/qrcode/lv_qrcode.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/qrcode/qrcodegen.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/rlottie/lv_rlottie.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/sjpg/lv_sjpg.c \
        ../Third_Party/LVGL/lvgl/src/extra/libs/sjpg/tjpgd.c \
        ../Third_Party/LVGL/lvgl/src/extra/lv_extra.c \
        ../Third_Party/LVGL/lvgl/src/extra/others/snapshot/lv_snapshot.c \
        ../Third_Party/LVGL/lvgl/src/extra/themes/basic/lv_theme_basic.c \
        ../Third_Party/LVGL/lvgl/src/extra/themes/default/lv_theme_default.c \
        ../Third_Party/LVGL/lvgl/src/extra/themes/mono/lv_theme_mono.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/animimg/lv_animimg.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/chart/lv_chart.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/led/lv_led.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/list/lv_list.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/meter/lv_meter.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/span/lv_span.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/spinner/lv_spinner.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/tabview/lv_tabview.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/tileview/lv_tileview.c \
        ../Third_Party/LVGL/lvgl/src/extra/widgets/win/lv_win.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_fmt_txt.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_loader.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_10.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_12.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_12_subpx.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_14.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_16.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_18.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_20.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_22.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_24.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_26.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_28.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_28_compressed.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_30.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_32.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_34.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_36.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_38.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_40.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_42.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_44.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_46.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_48.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_montserrat_8.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_simsun_16_cjk.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_unscii_16.c \
        ../Third_Party/LVGL/lvgl/src/font/lv_font_unscii_8.c \
        ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_pxp.c \
        ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_pxp_osa.c \
        ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_vglite.c \
        ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_sdl.c \
        ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_stm32_dma2d.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_arc.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_blend.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_img.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_label.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_line.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_draw_rect.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_lru.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_mask.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_stack_blur.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_texture_cache.c \
        ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_utils.c \
        ../Third_Party/LVGL/lvgl/src/hal/lv_hal_disp.c \
        ../Third_Party/LVGL/lvgl/src/hal/lv_hal_indev.c \
        ../Third_Party/LVGL/lvgl/src/hal/lv_hal_tick.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_anim.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_anim_timeline.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_area.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_async.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_bidi.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_color.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_fs.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_gc.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_ll.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_log.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_math.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_mem.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_printf.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_style.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_style_gen.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_templ.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_timer.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_tlsf.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_txt.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_txt_ap.c \
        ../Third_Party/LVGL/lvgl/src/misc/lv_utils.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_arc.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_bar.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_btn.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_btnmatrix.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_canvas.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_checkbox.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_dropdown.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_img.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_label.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_line.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_objx_templ.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_roller.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_slider.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_switch.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_table.c \
        ../Third_Party/LVGL/lvgl/src/widgets/lv_textarea.c \
        ../Third_Party/LVGL/lvgl/tests/src/lv_test_indev.c \
        ../Third_Party/LVGL/lvgl/tests/src/lv_test_init.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/_test_template.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_arc.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_checkbox.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_config.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_dropdown.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_font_loader.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_obj_tree.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_style.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_cases/test_txt.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_fonts/font_1.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_fonts/font_2.c \
        ../Third_Party/LVGL/lvgl/tests/src/test_fonts/font_3.c \
        ../Third_Party/LVGL/lvgl/tests/unity/unity.c \
        ../Third_Party/LVGL/lvgl/tests/unity/unity_support.c \
        lv_drivers/display/GC9A01.c \
        lv_drivers/display/ILI9341.c \
        lv_drivers/display/R61581.c \
        lv_drivers/display/SHARP_MIP.c \
        lv_drivers/display/SSD1963.c \
        lv_drivers/display/ST7565.c \
        lv_drivers/display/UC1610.c \
        lv_drivers/display/drm.c \
        lv_drivers/display/fbdev.c \
        lv_drivers/gtkdrv/gtkdrv.c \
        lv_drivers/indev/AD_touch.c \
        lv_drivers/indev/FT5406EE8.c \
        lv_drivers/indev/XPT2046.c \
        lv_drivers/indev/evdev.c \
        lv_drivers/indev/libinput.c \
        lv_drivers/indev/xkb.c \
        lv_drivers/sdl/sdl.c \
        lv_drivers/sdl/sdl_gpu.c \
        lv_drivers/wayland/wayland.c \
        lv_drivers/win32drv/win32drv.c \
        lv_drivers/win_drv.c \
        main.c \
        mouse_cursor_icon.c

HEADERS += \
    ../LVGL-APP/lvgl_app.h \
    ../Third_Party/LVGL/lvgl/examples/anim/lv_example_anim.h \
    ../Third_Party/LVGL/lvgl/examples/event/lv_example_event.h \
    ../Third_Party/LVGL/lvgl/examples/get_started/lv_example_get_started.h \
    ../Third_Party/LVGL/lvgl/examples/layouts/flex/lv_example_flex.h \
    ../Third_Party/LVGL/lvgl/examples/layouts/grid/lv_example_grid.h \
    ../Third_Party/LVGL/lvgl/examples/layouts/lv_example_layout.h \
    ../Third_Party/LVGL/lvgl/examples/libs/bmp/lv_example_bmp.h \
    ../Third_Party/LVGL/lvgl/examples/libs/freetype/lv_example_freetype.h \
    ../Third_Party/LVGL/lvgl/examples/libs/gif/lv_example_gif.h \
    ../Third_Party/LVGL/lvgl/examples/libs/lv_example_libs.h \
    ../Third_Party/LVGL/lvgl/examples/libs/png/lv_example_png.h \
    ../Third_Party/LVGL/lvgl/examples/libs/qrcode/lv_example_qrcode.h \
    ../Third_Party/LVGL/lvgl/examples/libs/rlottie/lv_example_rlottie.h \
    ../Third_Party/LVGL/lvgl/examples/libs/sjpg/lv_example_sjpg.h \
    ../Third_Party/LVGL/lvgl/examples/lv_examples.h \
    ../Third_Party/LVGL/lvgl/examples/others/lv_example_others.h \
    ../Third_Party/LVGL/lvgl/examples/others/snapshot/lv_example_snapshot.h \
    ../Third_Party/LVGL/lvgl/examples/porting/lv_port_disp_template.h \
    ../Third_Party/LVGL/lvgl/examples/porting/lv_port_fs_template.h \
    ../Third_Party/LVGL/lvgl/examples/porting/lv_port_indev_template.h \
    ../Third_Party/LVGL/lvgl/examples/scroll/lv_example_scroll.h \
    ../Third_Party/LVGL/lvgl/examples/styles/lv_example_style.h \
    ../Third_Party/LVGL/lvgl/examples/widgets/lv_example_widgets.h \
    ../Third_Party/LVGL/lvgl/lv_conf_template.h \
    ../Third_Party/LVGL/lvgl/lvgl.h \
    ../Third_Party/LVGL/lvgl/rt-thread/lv_rt_thread_conf.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_disp.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_event.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_group.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_indev.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_indev_scroll.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_class.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_draw.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_pos.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_scroll.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_style.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_style_gen.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_obj_tree.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_refr.h \
    ../Third_Party/LVGL/lvgl/src/core/lv_theme.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_arc.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_blend.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_img.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_label.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_line.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_mask.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_rect.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_draw_triangle.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_img_buf.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_img_cache.h \
    ../Third_Party/LVGL/lvgl/src/draw/lv_img_decoder.h \
    ../Third_Party/LVGL/lvgl/src/extra/layouts/flex/lv_flex.h \
    ../Third_Party/LVGL/lvgl/src/extra/layouts/grid/lv_grid.h \
    ../Third_Party/LVGL/lvgl/src/extra/layouts/lv_layouts.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/bmp/lv_bmp.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/freetype/lv_freetype.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/fsdrv/lv_fsdrv.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/gif/gifdec.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/gif/lv_gif.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/lv_libs.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/png/lodepng.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/png/lv_png.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/qrcode/lv_qrcode.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/qrcode/qrcodegen.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/rlottie/lv_rlottie.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/sjpg/lv_sjpg.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/sjpg/tjpgd.h \
    ../Third_Party/LVGL/lvgl/src/extra/libs/sjpg/tjpgdcnf.h \
    ../Third_Party/LVGL/lvgl/src/extra/lv_extra.h \
    ../Third_Party/LVGL/lvgl/src/extra/others/lv_others.h \
    ../Third_Party/LVGL/lvgl/src/extra/others/snapshot/lv_snapshot.h \
    ../Third_Party/LVGL/lvgl/src/extra/themes/basic/lv_theme_basic.h \
    ../Third_Party/LVGL/lvgl/src/extra/themes/default/lv_theme_default.h \
    ../Third_Party/LVGL/lvgl/src/extra/themes/lv_themes.h \
    ../Third_Party/LVGL/lvgl/src/extra/themes/mono/lv_theme_mono.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/animimg/lv_animimg.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/chart/lv_chart.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/keyboard/lv_keyboard.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/led/lv_led.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/list/lv_list.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/lv_widgets.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/meter/lv_meter.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/msgbox/lv_msgbox.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/span/lv_span.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/spinbox/lv_spinbox.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/spinner/lv_spinner.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/tabview/lv_tabview.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/tileview/lv_tileview.h \
    ../Third_Party/LVGL/lvgl/src/extra/widgets/win/lv_win.h \
    ../Third_Party/LVGL/lvgl/src/font/lv_font.h \
    ../Third_Party/LVGL/lvgl/src/font/lv_font_fmt_txt.h \
    ../Third_Party/LVGL/lvgl/src/font/lv_font_loader.h \
    ../Third_Party/LVGL/lvgl/src/font/lv_symbol_def.h \
    ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_pxp.h \
    ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_pxp_osa.h \
    ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_nxp_vglite.h \
    ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_sdl.h \
    ../Third_Party/LVGL/lvgl/src/gpu/lv_gpu_stm32_dma2d.h \
    ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_lru.h \
    ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_mask.h \
    ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_stack_blur.h \
    ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_texture_cache.h \
    ../Third_Party/LVGL/lvgl/src/gpu/sdl/lv_gpu_sdl_utils.h \
    ../Third_Party/LVGL/lvgl/src/hal/lv_hal.h \
    ../Third_Party/LVGL/lvgl/src/hal/lv_hal_disp.h \
    ../Third_Party/LVGL/lvgl/src/hal/lv_hal_indev.h \
    ../Third_Party/LVGL/lvgl/src/hal/lv_hal_tick.h \
    ../Third_Party/LVGL/lvgl/src/lv_api_map.h \
    ../Third_Party/LVGL/lvgl/src/lv_conf_internal.h \
    ../Third_Party/LVGL/lvgl/src/lv_conf_kconfig.h \
    ../Third_Party/LVGL/lvgl/src/lvgl.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_anim.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_anim_timeline.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_area.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_assert.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_async.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_bidi.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_color.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_fs.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_gc.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_ll.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_log.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_math.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_mem.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_printf.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_style.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_style_gen.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_templ.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_timer.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_tlsf.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_txt.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_txt_ap.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_types.h \
    ../Third_Party/LVGL/lvgl/src/misc/lv_utils.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_arc.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_bar.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_btn.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_btnmatrix.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_canvas.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_checkbox.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_dropdown.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_img.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_label.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_line.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_objx_templ.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_roller.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_slider.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_switch.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_table.h \
    ../Third_Party/LVGL/lvgl/src/widgets/lv_textarea.h \
    ../Third_Party/LVGL/lvgl/tests/src/lv_test_conf.h \
    ../Third_Party/LVGL/lvgl/tests/src/lv_test_indev.h \
    ../Third_Party/LVGL/lvgl/tests/src/lv_test_init.h \
    ../Third_Party/LVGL/lvgl/tests/unity/unity.h \
    ../Third_Party/LVGL/lvgl/tests/unity/unity_internals.h \
    ../Third_Party/LVGL/lvgl/tests/unity/unity_support.h \
    SDL2/SDL.h \
    SDL2/SDL_assert.h \
    SDL2/SDL_atomic.h \
    SDL2/SDL_audio.h \
    SDL2/SDL_bits.h \
    SDL2/SDL_blendmode.h \
    SDL2/SDL_clipboard.h \
    SDL2/SDL_config.h \
    SDL2/SDL_cpuinfo.h \
    SDL2/SDL_egl.h \
    SDL2/SDL_endian.h \
    SDL2/SDL_error.h \
    SDL2/SDL_events.h \
    SDL2/SDL_filesystem.h \
    SDL2/SDL_gamecontroller.h \
    SDL2/SDL_gesture.h \
    SDL2/SDL_haptic.h \
    SDL2/SDL_hidapi.h \
    SDL2/SDL_hints.h \
    SDL2/SDL_joystick.h \
    SDL2/SDL_keyboard.h \
    SDL2/SDL_keycode.h \
    SDL2/SDL_loadso.h \
    SDL2/SDL_locale.h \
    SDL2/SDL_log.h \
    SDL2/SDL_main.h \
    SDL2/SDL_messagebox.h \
    SDL2/SDL_metal.h \
    SDL2/SDL_misc.h \
    SDL2/SDL_mouse.h \
    SDL2/SDL_mutex.h \
    SDL2/SDL_name.h \
    SDL2/SDL_opengl.h \
    SDL2/SDL_opengl_glext.h \
    SDL2/SDL_opengles.h \
    SDL2/SDL_opengles2.h \
    SDL2/SDL_opengles2_gl2.h \
    SDL2/SDL_opengles2_gl2ext.h \
    SDL2/SDL_opengles2_gl2platform.h \
    SDL2/SDL_opengles2_khrplatform.h \
    SDL2/SDL_pixels.h \
    SDL2/SDL_platform.h \
    SDL2/SDL_power.h \
    SDL2/SDL_quit.h \
    SDL2/SDL_rect.h \
    SDL2/SDL_render.h \
    SDL2/SDL_revision.h \
    SDL2/SDL_rwops.h \
    SDL2/SDL_scancode.h \
    SDL2/SDL_sensor.h \
    SDL2/SDL_shape.h \
    SDL2/SDL_stdinc.h \
    SDL2/SDL_surface.h \
    SDL2/SDL_system.h \
    SDL2/SDL_syswm.h \
    SDL2/SDL_test.h \
    SDL2/SDL_test_assert.h \
    SDL2/SDL_test_common.h \
    SDL2/SDL_test_compare.h \
    SDL2/SDL_test_crc32.h \
    SDL2/SDL_test_font.h \
    SDL2/SDL_test_fuzzer.h \
    SDL2/SDL_test_harness.h \
    SDL2/SDL_test_images.h \
    SDL2/SDL_test_log.h \
    SDL2/SDL_test_md5.h \
    SDL2/SDL_test_memory.h \
    SDL2/SDL_test_random.h \
    SDL2/SDL_thread.h \
    SDL2/SDL_timer.h \
    SDL2/SDL_touch.h \
    SDL2/SDL_types.h \
    SDL2/SDL_version.h \
    SDL2/SDL_video.h \
    SDL2/SDL_vulkan.h \
    SDL2/begin_code.h \
    SDL2/close_code.h \
    lv_conf.h \
    lv_drivers/display/GC9A01.h \
    lv_drivers/display/ILI9341.h \
    lv_drivers/display/R61581.h \
    lv_drivers/display/SHARP_MIP.h \
    lv_drivers/display/SSD1963.h \
    lv_drivers/display/ST7565.h \
    lv_drivers/display/UC1610.h \
    lv_drivers/display/drm.h \
    lv_drivers/display/fbdev.h \
    lv_drivers/display/monitor.h \
    lv_drivers/gtkdrv/gtkdrv.h \
    lv_drivers/indev/AD_touch.h \
    lv_drivers/indev/FT5406EE8.h \
    lv_drivers/indev/XPT2046.h \
    lv_drivers/indev/evdev.h \
    lv_drivers/indev/keyboard.h \
    lv_drivers/indev/libinput_drv.h \
    lv_drivers/indev/mouse.h \
    lv_drivers/indev/mousewheel.h \
    lv_drivers/indev/xkb.h \
    lv_drivers/lv_drv_conf_template.h \
    lv_drivers/sdl/sdl.h \
    lv_drivers/sdl/sdl_gpu.h \
    lv_drivers/wayland/wayland.h \
    lv_drivers/win32drv/win32drv.h \
    lv_drivers/win_drv.h \
    lv_drv_conf.h
